project_name: 'mermaid-server'

builds:
  - main: './cmd/mermaid-server/main.go'
    binary: 'app'
    goos: ['linux', 'darwin', 'windows']
    goarch: ['386', 'amd64', 'arm', 'arm64']
    goarm: ['6', '7']

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch']

archives:
  - format_overrides:
    - goos: 'windows'
      format: 'zip'

nfpms:
  - formats: ['deb', 'rpm']
    dependencies: ['git']

dockers:
  - image_templates:
    - 'brunoluiz/mermaid-server:{{ .Tag }}'
    - 'brunoluiz/mermaid-server:v{{ .Major }}.{{ .Minor }}'
    - 'brunoluiz/mermaid-server:latest'
    dockerfile: 'Dockerfile.prod'
    binaries:
    - 'app'

brews:
  - github:
      owner: 'brunoluiz'
      name: 'homebrew-tap'
    folder: 'Formula'
